#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MUSIC_1                             100
#define IDR_MUSIC_2                             101
#define IDR_MUSIC_3                             102
#define IDR_MUSIC_4                             103
#define IDR_MUSIC_5                             104
#define IDR_MUSIC_6                             105
#define IDR_MUSIC_7                             106
#define IDR_MUSIC_8                             107
#define IDR_MUSIC_9                             108
#define IDR_MUSIC_10                            109
#define IDR_MUSIC_11                            110
#define IDR_MUSIC_12                            111
#define IDR_MUSIC_13                            112
#define IDR_MUSIC_14                            113
#define IDR_MUSIC_15                            114
#define IDR_MUSIC_16                            115
#define IDR_MUSIC_17                            116
#define IDR_MUSIC_18                            117
#define IDR_MUSIC_19                            118
#define IDR_MUSIC_20                            119
#define IDR_MUSIC_21                            120
#define IDR_MUSIC_22                            121
#define IDR_MUSIC_23                            122
#define IDR_MUSIC_24                            123
#define IDR_MUSIC_25                            124
#define IDR_MUSIC_26                            125
#define IDR_MUSIC_27                            126
#define IDR_MUSIC_28                            127
#define IDR_MUSIC_29                            128
#define IDR_MUSIC_30                            129
#define IDR_MUSIC_31                            130
#define IDR_MUSIC_32                            131
#define IDR_MUSIC_33                            132
#define IDR_MUSIC_34                            133
#define IDR_MUSIC_35                            134
#define IDR_MUSIC_36                            135
#define IDR_MUSIC_37                            136
#define IDR_MUSIC_38                            137
#define IDR_MUSIC_39                            138
#define IDR_MUSIC_40                            139
#define IDR_MUSIC_41                            140
#define IDR_MUSIC_42                            141
#define IDR_MUSIC_43                            142
#define IDR_MUSIC_44                            143
#define IDR_MUSIC_45                            144
#define IDR_MUSIC_46                            145
#define IDR_MUSIC_47                            146
#define IDR_MUSIC_48                            147
#define IDR_MUSIC_49                            148
#define IDR_MUSIC_50                            149
#define IDR_MUSIC_51                            150
#define IDR_MUSIC_52                            151
#define IDR_MUSIC_53                            152
#define IDR_MUSIC_54                            153
#define IDR_MUSIC_55                            154
#define IDR_MUSIC_56                            155
#define IDR_MUSIC_57                            156
#define IDR_MUSIC_58                            157
#define IDR_MUSIC_70                            169
#define IDR_MUSIC_71                            170
#define IDR_MUSIC_72                            171
#define IDR_MUSIC_73                            172
#define IDR_MUSIC_74                            173
#define IDR_MUSIC_75                            174
#define IDR_MUSIC_76                            175
#define IDR_MUSIC_77                            176
#define IDR_MUSIC_78                            177
#define IDR_MUSIC_79                            178
#define IDR_MUSIC_80                            179
#define IDR_MUSIC_81                            180
#define IDR_MUSIC_82                            181
#define IDR_MUSIC_83                            182
#define IDR_MUSIC_84                            183
#define IDR_MUSIC_85                            184
#define IDR_MUSIC_86                            185
#define IDR_MUSIC_87                            186
#define IDR_MUSIC_88                            187
#define IDR_MUSIC_89                            188
#define IDR_MUSIC_90                            189
#define IDR_MUSIC_91                            190
#define IDR_MUSIC_92                            191
#define IDR_MUSIC_93                            192
#define IDR_MUSIC_94                            193
#define IDR_MUSIC_95                            194
#define IDR_MUSIC_96                            195
#define IDR_DAC_81                              300
#define IDR_DAC_82                              301
#define IDR_DAC_86                              302
#define IDR_DAC_87                              303
#define IDR_DAC_88                              304
#define IDR_DAC_89                              305
#define IDR_DAC_8A                              306
#define IDR_DAC_8C                              307
#define IDR_DAC_8D                              308
#define IDR_DAC_8F                              309
#define IDR_DAC_90                              310
#define IDR_DAC_94                              311
#define IDR_DAC_98                              312
#define IDR_DAC_9B                              313
#define IDR_DAC_9C                              314
#define IDR_DAC_9D                              315
#define IDR_DAC_9E                              316
#define IDR_DAC_9F                              317
#define IDR_DAC_A0                              318
#define IDR_DAC_A1                              319
#define IDR_DAC_A2                              320
#define IDR_DAC_A3                              321
#define IDR_DAC_A4                              322
#define IDR_DAC_A5                              323
#define IDR_DAC_A6                              324
#define IDR_DAC_A7                              325
#define IDR_DAC_A8                              326
#define IDR_DAC_A9                              327
#define IDR_DAC_AA                              328
#define IDR_DAC_AB                              329
#define IDR_DAC_AC                              330
#define IDR_DAC_AD                              331
#define IDR_DAC_AF                              332
#define IDR_DAC_B0                              333
#define IDR_DAC_B1                              334
#define IDR_DAC_B2                              335
#define IDR_DAC_B4                              336
#define IDR_DAC_B5                              337
#define IDR_DAC_B6                              338
#define IDR_DAC_B7                              339
#define IDR_DAC_B8                              340
#define IDR_DAC_BA                              341
#define IDR_DAC_BB                              342
#define IDR_DAC_BC                              343
#define IDR_DAC_BD                              344
#define IDR_DAC_BE                              345
#define IDR_DAC_BF                              346
#define IDR_DAC_C0                              347
#define IDR_DAC_B2_S3                           348
#define IDR_DAC_9F_S3D                          349
#define IDR_DAC_A0_S3D                          350
#define IDR_DAC_81_S2                           351
#define IDR_DAC_82_S2                           352
#define IDR_DAC_83_S2                           353
#define IDR_DAC_84_S2                           354
#define IDR_DAC_85_S2                           355
#define IDR_DAC_86_S2                           356
#define IDR_DAC_87_S2                           357
#define IDR_MISC_INSSET                         400
#define IDR_MISC_MODULAT                        401
#define IDR_MISC_PSG_SK                         402
#define IDR_MISC_PSG_S3                         403
#define IDR_MISC_PSG_S2                         404
#define IDR_MISC_FM_DRUMS                       405
