#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MUSIC_1                             100
#define IDR_MUSIC_2                             101
#define IDR_MUSIC_3                             102
#define IDR_MUSIC_4                             103
#define IDR_MUSIC_5                             104
#define IDR_MUSIC_6                             105
#define IDR_MUSIC_7                             106
#define IDR_MUSIC_8                             107
#define IDR_MUSIC_9                             108
#define IDR_MUSIC_10                            109
#define IDR_MUSIC_11                            110
#define IDR_MUSIC_12                            111
#define IDR_MUSIC_13                            112
#define IDR_MUSIC_14                            113
#define IDR_MUSIC_15                            114
#define IDR_MUSIC_16                            115
#define IDR_MUSIC_17                            116
#define IDR_MUSIC_18                            117
#define IDR_MUSIC_19                            118
#define IDR_MUSIC_20                            119
#define IDR_MUSIC_21                            120
#define IDR_MUSIC_22                            121
#define IDR_MUSIC_23                            122
#define IDR_MUSIC_24                            123
#define IDR_MUSIC_25                            124
#define IDR_MUSIC_26                            125
#define IDR_MUSIC_27                            126
#define IDR_MUSIC_28                            127
#define IDR_MUSIC_29                            128
#define IDR_MUSIC_30                            129
#define IDR_MUSIC_31                            130
#define IDR_MUSIC_32                            131
#define IDR_MUSIC_33                            132
#define IDR_MUSIC_34                            133
#define IDR_MUSIC_35                            134
#define IDR_MUSIC_36                            135
#define IDR_MUSIC_37                            136
#define IDR_MUSIC_38                            137
#define IDR_MUSIC_39                            138
#define IDR_MUSIC_40                            139
#define IDR_MUSIC_41                            140
#define IDR_MUSIC_42                            141
#define IDR_MUSIC_43                            142
#define IDR_MUSIC_44                            143
#define IDR_MUSIC_45                            144
#define IDR_MUSIC_46                            145
#define IDR_MUSIC_47                            146
#define IDR_MUSIC_48                            147
#define IDR_MUSIC_49                            148
#define IDR_MUSIC_50                            149
#define IDR_MUSIC_51                            150
#define IDR_MUSIC_52                            151
#define IDR_MUSIC_53                            152
#define IDR_MUSIC_54                            153
#define IDR_MUSIC_55                            154
#define IDR_MUSIC_56                            155
#define IDR_MUSIC_57                            156
#define IDR_MUSIC_58                            157
#define IDR_MUSIC_70                            169
#define IDR_MUSIC_71                            170
#define IDR_MUSIC_72                            171
#define IDR_DAC_81                              200
#define IDR_DAC_82                              201
#define IDR_DAC_86                              202
#define IDR_DAC_87                              203
#define IDR_DAC_88                              204
#define IDR_DAC_89                              205
#define IDR_DAC_8A                              206
#define IDR_DAC_8C                              207
#define IDR_DAC_8D                              208
#define IDR_DAC_8F                              209
#define IDR_DAC_90                              210
#define IDR_DAC_94                              211
#define IDR_DAC_98                              212
#define IDR_DAC_9B                              213
#define IDR_DAC_9C                              214
#define IDR_DAC_9D                              215
#define IDR_DAC_9E                              216
#define IDR_DAC_9F                              217
#define IDR_DAC_A0                              218
#define IDR_DAC_A1                              219
#define IDR_DAC_A2                              220
#define IDR_DAC_A3                              221
#define IDR_DAC_A4                              222
#define IDR_DAC_A5                              223
#define IDR_DAC_A6                              224
#define IDR_DAC_A7                              225
#define IDR_DAC_A8                              226
#define IDR_DAC_A9                              227
#define IDR_DAC_AA                              228
#define IDR_DAC_AB                              229
#define IDR_DAC_AC                              230
#define IDR_DAC_AD                              231
#define IDR_DAC_AF                              232
#define IDR_DAC_B0                              233
#define IDR_DAC_B1                              234
#define IDR_DAC_B2                              235
#define IDR_DAC_B4                              236
#define IDR_DAC_B5                              237
#define IDR_DAC_B6                              238
#define IDR_DAC_B7                              239
#define IDR_DAC_B8                              240
#define IDR_DAC_BA                              241
#define IDR_DAC_BB                              242
#define IDR_DAC_BC                              243
#define IDR_DAC_BD                              244
#define IDR_DAC_BE                              245
#define IDR_DAC_BF                              246
#define IDR_DAC_C0                              247
#define IDR_DAC_B2_S3                           248
#define IDR_MISC_INSSET                         300
#define IDR_MISC_MODULAT                        301
#define IDR_MISC_PSG                            302
#define IDR_MISC_PSG_S3                         303
#define IDR_MISC_FM_DRUMS                       304
