#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MUSIC_1                             100
#define IDR_MUSIC_2                             101
#define IDR_MUSIC_3                             102
#define IDR_MUSIC_4                             103
#define IDR_MUSIC_5                             104
#define IDR_MUSIC_6                             105
#define IDR_MUSIC_7                             106
#define IDR_MUSIC_8                             107
#define IDR_MUSIC_9                             108
#define IDR_MUSIC_10                            109
#define IDR_MUSIC_11                            110
#define IDR_MUSIC_12                            111
#define IDR_MUSIC_13                            112
#define IDR_MUSIC_14                            113
#define IDR_MUSIC_15                            114
#define IDR_MUSIC_16                            115
#define IDR_MUSIC_17                            116
#define IDR_MUSIC_18                            117
#define IDR_MUSIC_19                            118
#define IDR_MUSIC_20                            119
#define IDR_MUSIC_21                            120
#define IDR_MUSIC_22                            121
#define IDR_MUSIC_23                            122
#define IDR_MUSIC_24                            123
#define IDR_MUSIC_25                            124
#define IDR_MUSIC_26                            125
#define IDR_MUSIC_27                            126
#define IDR_MUSIC_28                            127
#define IDR_MUSIC_29                            128
#define IDR_MUSIC_30                            129
#define IDR_MUSIC_31                            130
#define IDR_MUSIC_32                            131
#define IDR_MUSIC_33                            132
#define IDR_MUSIC_34                            133
#define IDR_MUSIC_35                            134
#define IDR_MUSIC_36                            135
#define IDR_MUSIC_37                            136
#define IDR_MUSIC_38                            137
#define IDR_MUSIC_39                            138
#define IDR_MUSIC_40                            139
#define IDR_MUSIC_41                            140
#define IDR_MUSIC_42                            141
#define IDR_MUSIC_43                            142
#define IDR_MUSIC_44                            143
#define IDR_MUSIC_45                            144
#define IDR_MUSIC_46                            145
#define IDR_MUSIC_47                            146
#define IDR_MUSIC_48                            147
#define IDR_MUSIC_49                            148
#define IDR_MUSIC_50                            149
#define IDR_MUSIC_51                            150
#define IDR_MUSIC_52                            151
#define IDR_MUSIC_53                            152
#define IDR_MUSIC_54                            153
#define IDR_MUSIC_55                            154
#define IDR_MUSIC_56                            155
#define IDR_DAC_81                              156
#define IDR_DAC_82                              157
#define IDR_DAC_86                              158
#define IDR_DAC_87                              159
#define IDR_DAC_88                              160
#define IDR_DAC_89                              161
#define IDR_DAC_8A                              162
#define IDR_DAC_8C                              163
#define IDR_DAC_8D                              164
#define IDR_DAC_8F                              165
#define IDR_DAC_90                              166
#define IDR_DAC_94                              167
#define IDR_DAC_98                              168
#define IDR_DAC_9B                              169
#define IDR_DAC_9C                              170
#define IDR_DAC_9D                              171
#define IDR_DAC_9E                              172
#define IDR_DAC_9F                              173
#define IDR_DAC_A0                              174
#define IDR_DAC_A1                              175
#define IDR_DAC_A2                              176
#define IDR_DAC_A3                              177
#define IDR_DAC_A4                              178
#define IDR_DAC_A5                              179
#define IDR_DAC_A6                              180
#define IDR_DAC_A7                              181
#define IDR_DAC_A8                              182
#define IDR_DAC_A9                              183
#define IDR_DAC_AA                              184
#define IDR_DAC_AB                              185
#define IDR_DAC_AC                              186
#define IDR_DAC_AD                              187
#define IDR_DAC_AF                              188
#define IDR_DAC_B0                              189
#define IDR_DAC_B1                              190
#define IDR_DAC_B2                              191
#define IDR_DAC_B4                              192
#define IDR_DAC_B5                              193
#define IDR_DAC_B6                              194
#define IDR_DAC_B7                              195
#define IDR_DAC_B8                              196
#define IDR_DAC_BA                              197
#define IDR_DAC_BB                              198
#define IDR_DAC_BC                              199
#define IDR_DAC_BD                              200
#define IDR_DAC_BE                              201
#define IDR_DAC_BF                              202
#define IDR_DAC_C0                              203
#define IDR_DAC_B2_S3                           204
#define IDR_MISC_INSSET                         205
#define IDR_MISC_MODULAT                        206
#define IDR_MISC_PSG                            207
#define IDR_MISC_PSG_S3                         208
