// This file was automatically generated by SMPSOUTBuildTool.

#include "songinfo.h"
#include "musicid.gen.h"

const musicentry MusicFiles[] = {
	{ 0xE18F, TrackMode_S3 },
	{ 0x8000, TrackMode_S3 },
	{ 0x9B6D, TrackMode_S3 },
	{ 0xB0BC, TrackMode_S3 },
	{ 0xC0C6, TrackMode_S3 },
	{ 0xD364, TrackMode_S3 },
	{ 0xD97B, TrackMode_S3 },
	{ 0xE48F, TrackMode_S3 },
	{ 0xDDA9, TrackMode_S3 },
	{ 0x8000, TrackMode_SK },
	{ 0x8597, TrackMode_SK },
	{ 0x86AA, TrackMode_S3 },
	{ 0x8000, TrackMode_S3 },
	{ 0x90CF, TrackMode_S3 },
	{ 0x8DC8, TrackMode_S3 },
	{ 0x8AFE, TrackMode_SK },
	{ 0x9106, TrackMode_SK },
	{ 0x9688, TrackMode_SK },
	{ 0x9CF2, TrackMode_SK },
	{ 0xA2E5, TrackMode_SK },
	{ 0xACF3, TrackMode_SK },
	{ 0xBE80, TrackMode_SK },
	{ 0xC2B4, TrackMode_SK },
	{ 0xC79F, TrackMode_SK },
	{ 0xCBB1, TrackMode_SK },
	{ 0xCEE1, TrackMode_SK },
	{ 0xD3DD, TrackMode_SK },
	{ 0xDCC0, TrackMode_SK },
	{ 0xE223, TrackMode_SK },
	{ 0xEABB, TrackMode_SK },
	{ 0x8AE8, TrackMode_S3 },
	{ 0x97FD, TrackMode_S3 },
	{ 0x99F7, TrackMode_S3 },
	{ 0xA4FD, TrackMode_S3 },
	{ 0xB0EC, TrackMode_S3 },
	{ 0xC324, TrackMode_S3 },
	{ 0xDA47, TrackMode_S3 },
	{ 0xDD4B, TrackMode_SK },
	{ 0xDFA6, TrackMode_SK },
	{ 0xE3C0, TrackMode_SK },
	{ 0xF095, TrackMode_S3 },
	{ 0xFE75, TrackMode_SK },
	{ 0xF364, TrackMode_S3 },
	{ 0xF5E4, TrackMode_S3 },
	{ 0xF1A0, TrackMode_S3 },
	{ 0xE7AF, TrackMode_SK },
	{ 0xF74C, TrackMode_SK },
	{ 0xFABE, TrackMode_SK },
	{ 0xFBFE, TrackMode_S3 },
	{ 0xE587, TrackMode_S3 },
	{ 0xF5A3, TrackMode_SK },
	{ 0xF88E, TrackMode_SK },
	{ 0xFD4B, TrackMode_SK },
	{ 0xE574, TrackMode_SK },
	{ 0xFCDE, TrackMode_SK },
	{ 0xC104, TrackMode_SK },
	{ 0xE33A, TrackMode_S3 },
	{ 0xEC7B, TrackMode_S3 },
	{ 0x8000, TrackMode_S3 },
	{ 0xC294, TrackMode_S3 },
	{ 0x84BD, TrackMode_S3 },
	{ 0x8024, TrackMode_S3D },
	{ 0x918F, TrackMode_S3D },
	{ 0xA8A0, TrackMode_S3D },
	{ 0xB9E7, TrackMode_S3D },
	{ 0xC795, TrackMode_S3D },
	{ 0xD04A, TrackMode_S3D },
	{ 0xD739, TrackMode_S3D },
	{ 0xE372, TrackMode_S3D },
	{ 0xF091, TrackMode_S3D },
	{ 0x8024, TrackMode_S3D },
	{ 0x8BDE, TrackMode_S3D },
	{ 0x96BD, TrackMode_S3D },
	{ 0xA0A8, TrackMode_S3D },
	{ 0xA8E0, TrackMode_S3D },
	{ 0x96B3, TrackMode_S3D },
	{ 0xBB55, TrackMode_S3D },
	{ 0xC68F, TrackMode_S3D },
	{ 0xD012, TrackMode_S3D },
	{ 0xD620, TrackMode_S3D },
	{ 0xDD98, TrackMode_S3D },
	{ 0xE1D9, TrackMode_S3D },
	{ 0x8D55, TrackMode_S3D },
	{ 0x9127, TrackMode_S3D },
	{ 0xCEC7, TrackMode_S3D },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x0000, TrackMode_S1 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0x1380, TrackMode_S2 },
	{ 0xD797, TrackMode_S2 },
	{ 0x802A, TrackMode_S2B },
	{ 0x85AC, TrackMode_S2B },
	{ 0x8D1D, TrackMode_S2B },
	{ 0x927A, TrackMode_S2B },
	{ 0x9DEE, TrackMode_S2B },
	{ 0xA49E, TrackMode_S2B },
	{ 0xA8E7, TrackMode_S2B },
	{ 0xB10A, TrackMode_S2B },
	{ 0xB778, TrackMode_S2B },
	{ 0xBD7F, TrackMode_S2B },
	{ 0xBED8, TrackMode_S2B },
	{ 0xC249, TrackMode_S2B },
	{ 0xC8AE, TrackMode_S2B },
	{ 0xCB08, TrackMode_S2B },
	{ 0xCF0B, TrackMode_S2B },
	{ 0xD322, TrackMode_S2B },
	{ 0xD73B, TrackMode_S2B },
	{ 0xDC54, TrackMode_S2B },
	{ 0xE0B7, TrackMode_S2B },
	{ 0xE3BE, TrackMode_S2B },
};

const trackoption TitleScreenTrackOptions[] = {
	{ "S3", MusicID_S3Title },
	{ "S&K", MusicID_SKTitle },
	{ "S&K0525", MusicID_SKTitle0525 },
	{ "S3D", MusicID_S3DIntro },
	{ "S1", MusicID_S1Title },
	{ "S2", MusicID_S2Title },
};

const trackoption AngelIsland1TrackOptions[] = {
	{ "S3K", MusicID_AngelIsland1 },
	{ "GreenGrove", MusicID_GreenGrove1 },
	{ "GreenHill", MusicID_GreenHill },
	{ "EmeraldHill", MusicID_EmeraldHill },
	{ "EmeraldHillBeta", MusicID_EmeraldHillBeta },
};

const trackoption AngelIsland2TrackOptions[] = {
	{ "S3K", MusicID_AngelIsland2 },
	{ "GreenGrove", MusicID_GreenGrove2 },
	{ "GreenHill", MusicID_GreenHill },
	{ "EmeraldHill", MusicID_EmeraldHill },
	{ "EmeraldHillBeta", MusicID_EmeraldHillBeta },
};

const trackoption Hydrocity1TrackOptions[] = {
	{ "S3K", MusicID_Hydrocity1 },
	{ "RustyRuin", MusicID_RustyRuin1 },
	{ "Labyrinth", MusicID_Labyrinth },
	{ "AquaticRuin", MusicID_AquaticRuin },
	{ "AquaticRuinBeta", MusicID_AquaticRuinBeta },
};

const trackoption Hydrocity2TrackOptions[] = {
	{ "S3K", MusicID_Hydrocity2 },
	{ "RustyRuin", MusicID_RustyRuin2 },
	{ "Labyrinth", MusicID_Labyrinth },
	{ "AquaticRuin", MusicID_AquaticRuin },
	{ "AquaticRuinBeta", MusicID_AquaticRuinBeta },
};

const trackoption MarbleGarden1TrackOptions[] = {
	{ "S3K", MusicID_MarbleGarden1 },
	{ "Marble", MusicID_Marble },
};

const trackoption MarbleGarden2TrackOptions[] = {
	{ "S3K", MusicID_MarbleGarden2 },
	{ "Marble", MusicID_Marble },
};

const trackoption CarnivalNight1TrackOptions[] = {
	{ "MD", MusicID_CarnivalNight1 },
	{ "SpringStadium", MusicID_SpringStadium1 },
	{ "SpringYard", MusicID_SpringYard },
	{ "CasinoNight", MusicID_CasinoNight },
	{ "CasinoNightBeta", MusicID_CasinoNightBeta },
};

const trackoption CarnivalNight2TrackOptions[] = {
	{ "MD", MusicID_CarnivalNight2 },
	{ "SpringStadium", MusicID_SpringStadium2 },
	{ "SpringYard", MusicID_SpringYard },
	{ "CasinoNight", MusicID_CasinoNight },
	{ "CasinoNightBeta", MusicID_CasinoNightBeta },
};

const trackoption FlyingBattery1TrackOptions[] = {
	{ "S3K", MusicID_FlyingBattery1 },
	{ "PanicPuppet", MusicID_PanicPuppet1 },
	{ "ScrapBrain", MusicID_ScrapBrain },
	{ "WingFortress", MusicID_WingFortress },
	{ "WingFortressBeta", MusicID_WingFortressBeta },
};

const trackoption FlyingBattery2TrackOptions[] = {
	{ "S3K", MusicID_FlyingBattery2 },
	{ "PanicPuppet", MusicID_PanicPuppet2 },
	{ "ScrapBrain", MusicID_ScrapBrain },
	{ "WingFortress", MusicID_WingFortress },
	{ "WingFortressBeta", MusicID_WingFortressBeta },
};

const trackoption IceCap1TrackOptions[] = {
	{ "MD", MusicID_IceCap1 },
	{ "DiamondDust", MusicID_DiamondDust1 },
};

const trackoption IceCap2TrackOptions[] = {
	{ "MD", MusicID_IceCap2 },
	{ "DiamondDust", MusicID_DiamondDust2 },
};

const trackoption LaunchBase1TrackOptions[] = {
	{ "MD", MusicID_LaunchBase1 },
	{ "GeneGadget", MusicID_GeneGadget1 },
	{ "PanicPuppet", MusicID_PanicPuppet1 },
	{ "ScrapBrain", MusicID_ScrapBrain },
	{ "Metropolis", MusicID_Metropolis },
	{ "ChemicalPlant", MusicID_ChemicalPlant },
	{ "MetropolisBeta", MusicID_MetropolisBeta },
	{ "ChemicalPlantBeta", MusicID_ChemicalPlantBeta },
};

const trackoption LaunchBase2TrackOptions[] = {
	{ "MD", MusicID_LaunchBase2 },
	{ "GeneGadget", MusicID_GeneGadget2 },
	{ "PanicPuppet", MusicID_PanicPuppet2 },
	{ "ScrapBrain", MusicID_ScrapBrain },
	{ "Metropolis", MusicID_Metropolis },
	{ "ChemicalPlant", MusicID_ChemicalPlant },
	{ "MetropolisBeta", MusicID_MetropolisBeta },
	{ "ChemicalPlantBeta", MusicID_ChemicalPlantBeta },
};

const trackoption MushroomHill1TrackOptions[] = {
	{ "S3K", MusicID_MushroomHill1 },
	{ "GreenGrove", MusicID_GreenGrove1 },
	{ "GreenHill", MusicID_GreenHill },
	{ "EmeraldHill", MusicID_EmeraldHill },
	{ "HillTop", MusicID_HillTop },
	{ "EmeraldHillBeta", MusicID_EmeraldHillBeta },
	{ "HillTopBeta", MusicID_HillTopBeta },
};

const trackoption MushroomHill2TrackOptions[] = {
	{ "S3K", MusicID_MushroomHill2 },
	{ "GreenGrove", MusicID_GreenGrove2 },
	{ "GreenHill", MusicID_GreenHill },
	{ "EmeraldHill", MusicID_EmeraldHill },
	{ "HillTop", MusicID_HillTop },
	{ "EmeraldHillBeta", MusicID_EmeraldHillBeta },
	{ "HillTopBeta", MusicID_HillTopBeta },
};

const trackoption Sandopolis1TrackOptions[] = {
	{ "S3K", MusicID_Sandopolis1 },
	{ "OilOcean", MusicID_OilOcean },
	{ "OilOceanBeta", MusicID_OilOceanBeta },
};

const trackoption Sandopolis2TrackOptions[] = {
	{ "S3K", MusicID_Sandopolis2 },
	{ "OilOcean", MusicID_OilOcean },
	{ "OilOceanBeta", MusicID_OilOceanBeta },
};

const trackoption LavaReef1TrackOptions[] = {
	{ "S3K", MusicID_LavaReef1 },
	{ "VolcanoValley", MusicID_VolcanoValley1 },
	{ "Marble", MusicID_Marble },
};

const trackoption LavaReef2TrackOptions[] = {
	{ "S3K", MusicID_LavaReef2 },
	{ "VolcanoValley", MusicID_VolcanoValley2 },
	{ "Marble", MusicID_Marble },
};

const trackoption SkySanctuaryTrackOptions[] = {
	{ "S3K", MusicID_SkySanctuary },
	{ "SkyChase", MusicID_SkyChase },
	{ "SkyChaseBeta", MusicID_SkyChaseBeta },
};

const trackoption DeathEgg1TrackOptions[] = {
	{ "S3K", MusicID_DeathEgg1 },
	{ "GeneGadget", MusicID_GeneGadget1 },
	{ "PanicPuppet", MusicID_PanicPuppet1 },
	{ "ScrapBrain", MusicID_ScrapBrain },
	{ "S2", MusicID_S2DeathEgg },
	{ "S2Beta", MusicID_S2DeathEggBeta },
};

const trackoption DeathEgg2TrackOptions[] = {
	{ "S3K", MusicID_DeathEgg2 },
	{ "GeneGadget", MusicID_GeneGadget2 },
	{ "PanicPuppet", MusicID_PanicPuppet2 },
	{ "ScrapBrain", MusicID_ScrapBrain },
	{ "S2", MusicID_S2DeathEgg },
	{ "S2Beta", MusicID_S2DeathEggBeta },
};

const trackoption MidbossTrackOptions[] = {
	{ "S3", MusicID_S3Midboss },
	{ "S&K", MusicID_SKMidboss },
	{ "S3D1", MusicID_S3DBoss1 },
	{ "S3D2", MusicID_S3DBoss2 },
	{ "S4E1", MusicID_S4E1Boss },
	{ "S1", MusicID_S1Boss },
	{ "S2", MusicID_S2Boss },
	{ "S2Beta", MusicID_S2BossBeta },
};

const trackoption BossTrackOptions[] = {
	{ "S3K", MusicID_Boss },
	{ "S3D1", MusicID_S3DBoss1 },
	{ "S3D2", MusicID_S3DBoss2 },
	{ "S4E1", MusicID_S4E1Boss },
	{ "S1", MusicID_S1Boss },
	{ "S2", MusicID_S2Boss },
	{ "S2Beta", MusicID_S2BossBeta },
};

const trackoption DoomsdayTrackOptions[] = {
	{ "S3K", MusicID_Doomsday },
	{ "S3D1", MusicID_S3DBoss1 },
	{ "S3D2", MusicID_S3DBoss2 },
	{ "FinalFight", MusicID_FinalFight },
	{ "S4E1", MusicID_S4E1Boss },
	{ "FinalZone", MusicID_FinalZone },
	{ "S2", MusicID_S2FinalBoss },
	{ "S2Beta", MusicID_S2FinalBossBeta },
};

const trackoption SpecialStageTrackOptions[] = {
	{ "S3K", MusicID_SpecialStage },
	{ "S3D", MusicID_S3DSpecialStage },
	{ "S1", MusicID_S1SpecialStage },
	{ "S2", MusicID_S2SpecialStage },
	{ "S2Beta", MusicID_S2SpecialStageBeta },
};

const trackoption SlotMachineTrackOptions[] = {
	{ "S3K", MusicID_SlotMachine },
	{ "S1", MusicID_S1SpecialStage },
};

const trackoption KnucklesTrackOptions[] = {
	{ "S3", MusicID_S3Knuckles },
	{ "S&K", MusicID_SKKnuckles },
};

const trackoption AzureLakeTrackOptions[] = {
	{ "S3K", MusicID_AzureLake },
	{ "EmeraldHill2P", MusicID_EmeraldHill2P },
	{ "EmeraldHill2PBeta", MusicID_EmeraldHill2PBeta },
};

const trackoption BalloonParkTrackOptions[] = {
	{ "S3K", MusicID_BalloonPark },
	{ "SpringStadium1", MusicID_SpringStadium1 },
	{ "SpringStadium2", MusicID_SpringStadium2 },
	{ "SpringYard", MusicID_SpringYard },
	{ "CasinoNight2P", MusicID_CasinoNight2P },
	{ "CasinoNight2PBeta", MusicID_CasinoNight2PBeta },
};

const trackoption DesertPalaceTrackOptions[] = {
	{ "S3K", MusicID_DesertPalace },
	{ "OilOcean", MusicID_OilOcean },
	{ "OilOceanBeta", MusicID_OilOceanBeta },
};

const trackoption ChromeGadgetTrackOptions[] = {
	{ "S3K", MusicID_ChromeGadget },
	{ "GeneGadget1", MusicID_GeneGadget1 },
	{ "GeneGadget2", MusicID_GeneGadget2 },
	{ "ScrapBrain", MusicID_ScrapBrain },
	{ "Metropolis", MusicID_Metropolis },
	{ "ChemicalPlant", MusicID_ChemicalPlant },
	{ "MetropolisBeta", MusicID_MetropolisBeta },
	{ "ChemicalPlantBeta", MusicID_ChemicalPlantBeta },
};

const trackoption EndlessMineTrackOptions[] = {
	{ "S3K", MusicID_EndlessMine },
	{ "MysticCave", MusicID_MysticCave },
	{ "MysticCave2P", MusicID_MysticCave2P },
	{ "MysticCaveBeta", MusicID_MysticCaveBeta },
	{ "MysticCave2PBeta", MusicID_MysticCave2PBeta },
};

const trackoption GameOverTrackOptions[] = {
	{ "S3K", MusicID_GameOver },
	{ "S1", MusicID_S1GameOver },
};

const trackoption ContinueTrackOptions[] = {
	{ "S3", MusicID_S3Continue },
	{ "S&K", MusicID_Continue },
	{ "S1", MusicID_S1Continue },
	{ "S22PResults", MusicID_S22PResults },
	{ "S22PResultsBeta", MusicID_S22PResultsBeta },
};

const trackoption ActClearTrackOptions[] = {
	{ "S3K", MusicID_ActClear },
	{ "S1", MusicID_S1ActClear },
};

const trackoption OneUpTrackOptions[] = {
	{ "S3", MusicID_S31Up },
	{ "S&K", MusicID_SK1Up },
	{ "S1", MusicID_S11Up },
};

const trackoption InvincibilityTrackOptions[] = {
	{ "S3", MusicID_S3Invincibility },
	{ "S&K", MusicID_SKInvincibility },
	{ "S3D", MusicID_S3DInvincibility },
	{ "S1", MusicID_S1Invincibility },
	{ "S2SuperSonic", MusicID_S2SuperSonic },
	{ "S2", MusicID_S2Invincibility },
	{ "S2SuperSonicBeta", MusicID_S2SuperSonicBeta },
};

const trackoption CompetitionMenuTrackOptions[] = {
	{ "MD", MusicID_CompetitionMenu },
	{ "S3D", MusicID_S3DMenu },
	{ "S2Options", MusicID_S2Options },
	{ "S22PResults", MusicID_S22PResults },
	{ "S2OptionsBeta", MusicID_S2OptionsBeta },
	{ "S22PResultsBeta", MusicID_S22PResultsBeta },
};

const trackoption LevelSelectTrackOptions[] = {
	{ "S3K", MusicID_LevelSelect },
	{ "S3D", MusicID_S3DMenu },
	{ "PanicPuppet1", MusicID_PanicPuppet1 },
	{ "S2", MusicID_S2Options },
	{ "S2Beta", MusicID_S2OptionsBeta },
};

const trackoption FinalBossTrackOptions[] = {
	{ "S3K", MusicID_FinalBoss },
	{ "S3D1", MusicID_S3DBoss1 },
	{ "S3D2", MusicID_S3DBoss2 },
	{ "FinalFight", MusicID_FinalFight },
	{ "S4E1", MusicID_S4E1Boss },
	{ "FinalZone", MusicID_FinalZone },
	{ "S2", MusicID_S2FinalBoss },
	{ "S2Beta", MusicID_S2FinalBossBeta },
};

const trackoption AllClearTrackOptions[] = {
	{ "S3", MusicID_S3AllClear },
	{ "S&K", MusicID_SKAllClear },
	{ "S&K0525", MusicID_SKAllClear0525 },
	{ "S3D", MusicID_S3DEnding },
	{ "S1", MusicID_S1Ending },
	{ "S2", MusicID_S2Ending },
};

const trackoption CreditsTrackOptions[] = {
	{ "S3", MusicID_S3Credits },
	{ "S&K", MusicID_SKCredits },
	{ "S3C", MusicID_S3CCredits },
	{ "S&K0525", MusicID_SKCredits0525 },
	{ "S3D", MusicID_S3DCredits },
	{ "S1", MusicID_S1Credits },
	{ "S2", MusicID_S2Credits },
};

const trackoption HiddenPalaceTrackOptions[] = {
	{ "S3K", MusicID_LavaReef2 },
	{ "S2HiddenPalace", MusicID_S2HiddenPalace },
};

const trackoption SuperSonicTrackOptions[] = {
	{ "S3", MusicID_S3Invincibility },
	{ "S&K", MusicID_SKInvincibility },
	{ "S3D", MusicID_S3DInvincibility },
	{ "S1", MusicID_S1Invincibility },
	{ "S2", MusicID_S2SuperSonic },
	{ "S2Invincibility", MusicID_S2Invincibility },
	{ "S2Beta", MusicID_S2SuperSonicBeta },
};

const trackoption EndingTrackOptions[] = {
	{ "SkySanctuary", MusicID_SkySanctuary },
	{ "S3Credits", MusicID_S3Credits },
	{ "S1", MusicID_S1Ending },
	{ "S2", MusicID_S2Ending },
	{ "S3D", MusicID_S3DEnding },
};

const trackoption DataSelectTrackOptions[] = {
	{ "S3K", MusicID_LevelSelect },
	{ "S3D", MusicID_S3DMenu },
	{ "PanicPuppet1", MusicID_PanicPuppet1 },
	{ "S2", MusicID_S2Options },
	{ "S2Beta", MusicID_S2OptionsBeta },
};

const tracknameoptions TrackOptions[] = {
	trackoptdef(TitleScreenTrack),
	trackoptdef(AngelIsland1Track),
	trackoptdef(AngelIsland2Track),
	trackoptdef(Hydrocity1Track),
	trackoptdef(Hydrocity2Track),
	trackoptdef(MarbleGarden1Track),
	trackoptdef(MarbleGarden2Track),
	trackoptdef(CarnivalNight1Track),
	trackoptdef(CarnivalNight2Track),
	trackoptdef(FlyingBattery1Track),
	trackoptdef(FlyingBattery2Track),
	trackoptdef(IceCap1Track),
	trackoptdef(IceCap2Track),
	trackoptdef(LaunchBase1Track),
	trackoptdef(LaunchBase2Track),
	trackoptdef(MushroomHill1Track),
	trackoptdef(MushroomHill2Track),
	trackoptdef(Sandopolis1Track),
	trackoptdef(Sandopolis2Track),
	trackoptdef(LavaReef1Track),
	trackoptdef(LavaReef2Track),
	trackoptdef(SkySanctuaryTrack),
	trackoptdef(DeathEgg1Track),
	trackoptdef(DeathEgg2Track),
	trackoptdef(MidbossTrack),
	trackoptdef(BossTrack),
	trackoptdef(DoomsdayTrack),
	{ "MagneticOrbsTrack" },
	trackoptdef(SpecialStageTrack),
	trackoptdef(SlotMachineTrack),
	{ "GumballMachineTrack" },
	trackoptdef(KnucklesTrack),
	trackoptdef(AzureLakeTrack),
	trackoptdef(BalloonParkTrack),
	trackoptdef(DesertPalaceTrack),
	trackoptdef(ChromeGadgetTrack),
	trackoptdef(EndlessMineTrack),
	trackoptdef(GameOverTrack),
	trackoptdef(ContinueTrack),
	trackoptdef(ActClearTrack),
	trackoptdef(OneUpTrack),
	{ "ChaosEmeraldTrack" },
	trackoptdef(InvincibilityTrack),
	trackoptdef(CompetitionMenuTrack),
	{ "UnusedTrack" },
	trackoptdef(LevelSelectTrack),
	trackoptdef(FinalBossTrack),
	{ "DrowningTrack" },
	trackoptdef(AllClearTrack),
	trackoptdef(CreditsTrack),
	trackoptdef(KnucklesTrack),
	trackoptdef(TitleScreenTrack),
	trackoptdef(OneUpTrack),
	trackoptdef(InvincibilityTrack),
	trackoptdef(AllClearTrack),
	trackoptdef(CreditsTrack),
	trackoptdef(HiddenPalaceTrack),
	trackoptdef(SuperSonicTrack),
	trackoptdef(EndingTrack),
	trackoptdef(DataSelectTrack),
};
