#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_DAC_81                              100
#define IDR_DAC_82                              101
#define IDR_DAC_86                              102
#define IDR_DAC_87                              103
#define IDR_DAC_88                              104
#define IDR_DAC_89                              105
#define IDR_DAC_8A                              106
#define IDR_DAC_8C                              107
#define IDR_DAC_8D                              108
#define IDR_DAC_8F                              109
#define IDR_DAC_90                              110
#define IDR_DAC_94                              111
#define IDR_DAC_98                              112
#define IDR_DAC_9B                              113
#define IDR_DAC_9C                              114
#define IDR_DAC_9D                              115
#define IDR_DAC_9E                              116
#define IDR_DAC_9F                              117
#define IDR_DAC_A0                              118
#define IDR_DAC_A1                              119
#define IDR_DAC_A2                              120
#define IDR_DAC_A3                              121
#define IDR_DAC_A4                              122
#define IDR_DAC_A5                              123
#define IDR_DAC_A6                              124
#define IDR_DAC_A7                              125
#define IDR_DAC_A8                              126
#define IDR_DAC_A9                              127
#define IDR_DAC_AA                              128
#define IDR_DAC_AB                              129
#define IDR_DAC_AC                              130
#define IDR_DAC_AD                              131
#define IDR_DAC_AF                              132
#define IDR_DAC_B0                              133
#define IDR_DAC_B1                              134
#define IDR_DAC_B2                              135
#define IDR_DAC_B4                              136
#define IDR_DAC_B5                              137
#define IDR_DAC_B6                              138
#define IDR_DAC_B7                              139
#define IDR_DAC_B8                              140
#define IDR_DAC_BA                              141
#define IDR_DAC_BB                              142
#define IDR_DAC_BC                              143
#define IDR_DAC_BD                              144
#define IDR_DAC_BE                              145
#define IDR_DAC_BF                              146
#define IDR_DAC_C0                              147
#define IDR_DAC_B2_S3                           148
#define IDR_DAC_9B_S3PROTO                      149
#define IDR_DAC_9F_S3D                          150
#define IDR_DAC_A0_S3D                          151
#define IDR_DAC_81_S2                           152
#define IDR_DAC_82_S2                           153
#define IDR_DAC_83_S2                           154
#define IDR_DAC_84_S2                           155
#define IDR_DAC_85_S2                           156
#define IDR_DAC_86_S2                           157
#define IDR_DAC_87_S2                           158
#define IDR_MISC_INSSET                         200
#define IDR_MISC_MODENV_S3K                     201
#define IDR_MISC_MODENV_S3PROTO                 202
#define IDR_MISC_VOLENV_SK                      203
#define IDR_MISC_VOLENV_S3                      204
#define IDR_MISC_VOLENV_S2                      205
#define IDR_MISC_FM_DRUMS                       206
